# ============================================================
# LD2410 Component with Automatic Calibration
# ============================================================

substitutions:
  tx_pin: TX                      # replace with your TX pin
  rx_pin: RX                      # replace with your RX pin
  default_collection_seconds: 30  # how many seconds to collect calibration data
  default_move_margin: 2          # default threshold margin to add on top of maxima
  default_still_margin: 1         # default threshold margin to add on top of maxima
  
  # fixed gate values, "-1" = "not set"
  g0_move: 50
  g1_move: 50
  g2_move: -1
  g3_move: -1
  g4_move: -1
  g5_move: -1
  g6_move: -1
  g7_move: -1
  g8_move: -1
  g0_still: 0
  g1_still: 0
  g2_still: -1
  g3_still: -1
  g4_still: -1
  g5_still: -1
  g6_still: -1
  g7_still: -1
  g8_still: -1

##########################
# Globals to store maxima
##########################
globals:
  # Move energy maxima per gate
  - { id: max_g0_move, type: int, initial_value: '0' }
  - { id: max_g1_move, type: int, initial_value: '0' }
  - { id: max_g2_move, type: int, initial_value: '0' }
  - { id: max_g3_move, type: int, initial_value: '0' }
  - { id: max_g4_move, type: int, initial_value: '0' }
  - { id: max_g5_move, type: int, initial_value: '0' }
  - { id: max_g6_move, type: int, initial_value: '0' }
  - { id: max_g7_move, type: int, initial_value: '0' }
  - { id: max_g8_move, type: int, initial_value: '0' }

  # Still energy maxima per gate
  - { id: max_g0_still, type: int, initial_value: '0' }
  - { id: max_g1_still, type: int, initial_value: '0' }
  - { id: max_g2_still, type: int, initial_value: '0' }
  - { id: max_g3_still, type: int, initial_value: '0' }
  - { id: max_g4_still, type: int, initial_value: '0' }
  - { id: max_g5_still, type: int, initial_value: '0' }
  - { id: max_g6_still, type: int, initial_value: '0' }
  - { id: max_g7_still, type: int, initial_value: '0' }
  - { id: max_g8_still, type: int, initial_value: '0' }

  # Move energy fixed values per gate
  - { id: fixed_g0_move, type: std::string, initial_value: '"${g0_move}"' }
  - { id: fixed_g1_move, type: std::string, initial_value: '"${g1_move}"' }
  - { id: fixed_g2_move, type: std::string, initial_value: '"${g2_move}"' }
  - { id: fixed_g3_move, type: std::string, initial_value: '"${g3_move}"' }
  - { id: fixed_g4_move, type: std::string, initial_value: '"${g4_move}"' }
  - { id: fixed_g5_move, type: std::string, initial_value: '"${g5_move}"' }
  - { id: fixed_g6_move, type: std::string, initial_value: '"${g6_move}"' }
  - { id: fixed_g7_move, type: std::string, initial_value: '"${g7_move}"' }
  - { id: fixed_g8_move, type: std::string, initial_value: '"${g8_move}"' }

  # Still energy fixed values per gate
  - { id: fixed_g0_still, type: std::string, initial_value: '"${g0_still}"' }
  - { id: fixed_g1_still, type: std::string, initial_value: '"${g1_still}"' }
  - { id: fixed_g2_still, type: std::string, initial_value: '"${g2_still}"' }
  - { id: fixed_g3_still, type: std::string, initial_value: '"${g3_still}"' }
  - { id: fixed_g4_still, type: std::string, initial_value: '"${g4_still}"' }
  - { id: fixed_g5_still, type: std::string, initial_value: '"${g5_still}"' }
  - { id: fixed_g6_still, type: std::string, initial_value: '"${g6_still}"' }
  - { id: fixed_g7_still, type: std::string, initial_value: '"${g7_still}"' }
  - { id: fixed_g8_still, type: std::string, initial_value: '"${g8_still}"' }

##########################
# Logger
##########################
logger:
  baud_rate: 0

##########################
# UART & LD2410
##########################
uart:
  id: ld2410_uart
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 256000
  parity: none
  stop_bits: 1

ld2410:
  id: ld2410_sensor
  uart_id: ld2410_uart

##########################
# Switch for engineering mode
##########################
switch:
  - platform: ld2410
    engineering_mode:
      name: Engineering Mode
      id: ld2410_eng_mode

##########################
# Sensors for LD2410 data
##########################
sensor:
  - platform: ld2410
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

    # Gate energy sensors
    g0:
      move_energy: { id: g0_move_energy, name: G0 move energy }
      still_energy: { id: g0_still_energy, name: G0 still energy }
    g1:
      move_energy: { id: g1_move_energy, name: G1 move energy }
      still_energy: { id: g1_still_energy, name: G1 still energy }
    g2:
      move_energy: { id: g2_move_energy, name: G2 move energy }
      still_energy: { id: g2_still_energy, name: G2 still energy }
    g3:
      move_energy: { id: g3_move_energy, name: G3 move energy }
      still_energy: { id: g3_still_energy, name: G3 still energy }
    g4:
      move_energy: { id: g4_move_energy, name: G4 move energy }
      still_energy: { id: g4_still_energy, name: G4 still energy }
    g5:
      move_energy: { id: g5_move_energy, name: G5 move energy }
      still_energy: { id: g5_still_energy, name: G5 still energy }
    g6:
      move_energy: { id: g6_move_energy, name: G6 move energy }
      still_energy: { id: g6_still_energy, name: G6 still energy }
    g7:
      move_energy: { id: g7_move_energy, name: G7 move energy }
      still_energy: { id: g7_still_energy, name: G7 still energy }
    g8:
      move_energy: { id: g8_move_energy, name: G8 move energy }
      still_energy: { id: g8_still_energy, name: G8 still energy }

binary_sensor:
  - platform: ld2410
    has_target:
      name: Detection Presence

##########################
# Threshold numbers per gate
##########################
number:
  - platform: ld2410
    timeout: { name: Timeout, mode: box }
    light_threshold: { name: Light threshold, mode: box }
    max_move_distance_gate: { name: Max move distance gate, mode: box }
    max_still_distance_gate: { name: Max still distance gate, mode: box }

    g0:
      move_threshold: { id: g0_move_threshold, name: G0 move threshold, mode: box }
      still_threshold: { id: g0_still_threshold, name: G0 still threshold, mode: box }
    g1:
      move_threshold: { id: g1_move_threshold, name: G1 move threshold, mode: box }
      still_threshold: { id: g1_still_threshold, name: G1 still threshold, mode: box }
    g2:
      move_threshold: { id: g2_move_threshold, name: G2 move threshold, mode: box }
      still_threshold: { id: g2_still_threshold, name: G2 still threshold, mode: box }
    g3:
      move_threshold: { id: g3_move_threshold, name: G3 move threshold, mode: box }
      still_threshold: { id: g3_still_threshold, name: G3 still threshold, mode: box }
    g4:
      move_threshold: { id: g4_move_threshold, name: G4 move threshold, mode: box }
      still_threshold: { id: g4_still_threshold, name: G4 still threshold, mode: box }
    g5:
      move_threshold: { id: g5_move_threshold, name: G5 move threshold, mode: box }
      still_threshold: { id: g5_still_threshold, name: G5 still threshold, mode: box }
    g6:
      move_threshold: { id: g6_move_threshold, name: G6 move threshold, mode: box }
      still_threshold: { id: g6_still_threshold, name: G6 still threshold, mode: box }
    g7:
      move_threshold: { id: g7_move_threshold, name: G7 move threshold, mode: box }
      still_threshold: { id: g7_still_threshold, name: G7 still threshold, mode: box }
    g8:
      move_threshold: { id: g8_move_threshold, name: G8 move threshold, mode: box }
      still_threshold: { id: g8_still_threshold, name: G8 still threshold, mode: box }

  # User-configurable margin added to maxima
  - platform: template
    name: "Move Margin"
    id: ld2410_move_margin
    mode: box
    optimistic: true
    initial_value: ${default_move_margin}
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    name: "Still Margin"
    id: ld2410_still_margin
    mode: box
    optimistic: true
    initial_value: ${default_still_margin}
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    name: "Collection Seconds"
    id: ld2410_collection_seconds
    mode: box
    optimistic: true
    initial_value: ${default_collection_seconds}
    min_value: 0
    max_value: 100
    step: 1

##########################
# Report sensor
##########################
text_sensor:
  - platform: template
    name: "Calibration Report"
    id: ld2410_max_report
    icon: "mdi:radar"

##########################
# Buttons
##########################
button:
  # Built-in LD2410 controls
  - platform: ld2410
    factory_reset: { name: "Factory Reset" }
    restart: { name: "Restart" }
    query_params: { name: "Query Params" }

  # Start calibration button
  - platform: template
    name: "Start Calibration"
    id: start_collection_button
    on_press:
      then:
        - switch.turn_on: ld2410_eng_mode
        - delay: 500ms
        - lambda: |-
            // Reset all maxima
            id(max_g0_move)=id(max_g1_move)=id(max_g2_move)=id(max_g3_move)=id(max_g4_move)=0;
            id(max_g5_move)=id(max_g6_move)=id(max_g7_move)=id(max_g8_move)=0;
            id(max_g0_still)=id(max_g1_still)=id(max_g2_still)=id(max_g3_still)=id(max_g4_still)=0;
            id(max_g5_still)=id(max_g6_still)=id(max_g7_still)=id(max_g8_still)=0;
        - repeat:
            count: !lambda "return id(ld2410_collection_seconds).state;"
            then:
              - delay: 1s
              - lambda: |-
                  // Helper lambda to update maxima
                  auto update = [](int &maxv, float current) {
                    int v = (int)round(current);
                    if (v > maxv) maxv = v;
                  };

                  // Update all move gates
                  update(id(max_g0_move), id(g0_move_energy).state);
                  update(id(max_g1_move), id(g1_move_energy).state);
                  update(id(max_g2_move), id(g2_move_energy).state);
                  update(id(max_g3_move), id(g3_move_energy).state);
                  update(id(max_g4_move), id(g4_move_energy).state);
                  update(id(max_g5_move), id(g5_move_energy).state);
                  update(id(max_g6_move), id(g6_move_energy).state);
                  update(id(max_g7_move), id(g7_move_energy).state);
                  update(id(max_g8_move), id(g8_move_energy).state);

                  // Update all still gates
                  update(id(max_g0_still), id(g0_still_energy).state);
                  update(id(max_g1_still), id(g1_still_energy).state);
                  update(id(max_g2_still), id(g2_still_energy).state);
                  update(id(max_g3_still), id(g3_still_energy).state);
                  update(id(max_g4_still), id(g4_still_energy).state);
                  update(id(max_g5_still), id(g5_still_energy).state);
                  update(id(max_g6_still), id(g6_still_energy).state);
                  update(id(max_g7_still), id(g7_still_energy).state);
                  update(id(max_g8_still), id(g8_still_energy).state);

                  // Update text report
                  id(update_report).execute();
        - switch.turn_off: ld2410_eng_mode

  # Apply thresholds button
  - platform: template
    name: "Apply Config"
    on_press:
      then:
        - lambda: |-
            int move_margin = (int)id(ld2410_move_margin).state;
            int still_margin = (int)id(ld2410_still_margin).state;

            std::array<esphome::number::Number*,9> move_nums = {
              id(g0_move_threshold), id(g1_move_threshold), id(g2_move_threshold),
              id(g3_move_threshold), id(g4_move_threshold), id(g5_move_threshold),
              id(g6_move_threshold), id(g7_move_threshold), id(g8_move_threshold)
            };
            std::array<esphome::number::Number*,9> still_nums = {
              id(g0_still_threshold), id(g1_still_threshold), id(g2_still_threshold),
              id(g3_still_threshold), id(g4_still_threshold), id(g5_still_threshold),
              id(g6_still_threshold), id(g7_still_threshold), id(g8_still_threshold)
            };

            std::array<int,9> max_move = {
              id(max_g0_move), id(max_g1_move), id(max_g2_move),
              id(max_g3_move), id(max_g4_move), id(max_g5_move),
              id(max_g6_move), id(max_g7_move), id(max_g8_move)
            };
            std::array<std::string ,9> fixed_move = {
              id(fixed_g0_move), id(fixed_g1_move), id(fixed_g2_move),
              id(fixed_g3_move), id(fixed_g4_move), id(fixed_g5_move),
              id(fixed_g6_move), id(fixed_g7_move), id(fixed_g8_move)
            };

            std::array<int,9> max_still = {
              id(max_g0_still), id(max_g1_still), id(max_g2_still),
              id(max_g3_still), id(max_g4_still), id(max_g5_still),
              id(max_g6_still), id(max_g7_still), id(max_g8_still)
            };
            std::array<std::string ,9> fixed_still = {
              id(fixed_g0_still), id(fixed_g1_still), id(fixed_g2_still),
              id(fixed_g3_still), id(fixed_g4_still), id(fixed_g5_still),
              id(fixed_g6_still), id(fixed_g7_still), id(fixed_g8_still)
            };

            for (int i = 0; i < 9; i++) {
              int move_val  = fixed_move[i] != "-1" ? atoi(fixed_move[i].c_str()) : max_move[i] + move_margin;
              int still_val = fixed_still[i] != "-1" ? atoi(fixed_still[i].c_str()) : max_still[i] + still_margin;

              move_nums[i]->make_call().set_value((float)move_val).perform();
              still_nums[i]->make_call().set_value((float)still_val).perform();
            }

            ESP_LOGI("ld2410", "Applied thresholds (defaults if set, otherwise maxima) + margins");
##########################
# Scripts
##########################
script:
  # Builds and publishes a text report of maxima
  - id: update_report
    then:
      - lambda: |-
          char buf[512];
          snprintf(buf, sizeof(buf),
            "Move: %d,%d,%d,%d,%d,%d,%d,%d,%d | Still: %d,%d,%d,%d,%d,%d,%d,%d,%d",
            id(max_g0_move), id(max_g1_move), id(max_g2_move), id(max_g3_move), id(max_g4_move),
            id(max_g5_move), id(max_g6_move), id(max_g7_move), id(max_g8_move),
            id(max_g0_still), id(max_g1_still), id(max_g2_still), id(max_g3_still), id(max_g4_still),
            id(max_g5_still), id(max_g6_still), id(max_g7_still), id(max_g8_still)
          );
          id(ld2410_max_report).publish_state(std::string(buf));     
          ESP_LOGI("ld2410", "%s", buf);